### ISSUE TITLE
remove nose

### ISSUE THREAD

**Issue by pgajdos** [ronnyandersson/zignal#9]
Hi,
could you please consider to remove imports, nose code in `__main__` and dependency on deprecated nose? Tests run just fine with pytest for example.

**Comment by ronnyandersson** [comment]
Hi,

Sorry for late answer. I made the decision a long time ago to use nose instead of the built in unit test framework. I cannot even remember the argument for using nose any more and I will revisit the unit tests at some point. Back then nose had some features that made it the best choice but that might not be the case any more.

**Comment by pgajdos** [comment]
Thanks
